version: "3.8"

services:

  backend1:
    build: ./backend

  backend2:
    build: ./backend

  backend3:
    build: ./backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
